// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20200920075042_Add_Coords")]
    partial class Add_Coords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 13,
                            Body = "In vitae aliquid porro.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(4036),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(5527)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 7,
                            Body = "Et et est iste.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7358),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7430)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 21,
                            Body = "Quia quia ipsa.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7617),
                            IsDeleted = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7639)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Body = "Dolorem molestiae ut omnis maxime exercitationem sit.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7921),
                            IsDeleted = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(7950)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 12,
                            Body = "Ipsam dolorem enim exercitationem.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8206),
                            IsDeleted = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8232)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 13,
                            Body = "Qui laboriosam aut voluptate iure veniam voluptatem corporis voluptate.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8523),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8546)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 12,
                            Body = "Impedit maxime et.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8903),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(8927)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 21,
                            Body = "Ut perspiciatis deserunt.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9150)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 16,
                            Body = "Amet maxime ex voluptate.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9347),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9373)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Error ipsum quos ipsam et unde quia omnis qui.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9662),
                            IsDeleted = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9691)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 15,
                            Body = "Nobis expedita sapiente quae in.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 673, DateTimeKind.Local).AddTicks(9977),
                            IsDeleted = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(4)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 16,
                            Body = "Numquam iste quos et.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(216),
                            IsDeleted = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(239)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 5,
                            Body = "Modi rerum non voluptates in esse placeat quibusdam rerum.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(542),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(562)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 15,
                            Body = "Doloribus doloremque corporis eum quia dolores harum et atque modi.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1032),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1061)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            Body = "Odio fugiat facilis aut cum dolore iste id.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1343),
                            IsDeleted = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1368)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 20,
                            Body = "Numquam nemo aut et.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1581),
                            IsDeleted = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1608)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            Body = "Eum ut quo.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1805),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(1836)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            Body = "Qui ipsum aut consequuntur in iure repellat earum aut sed.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2168),
                            IsDeleted = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2187)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            Body = "Temporibus quia ut.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2390),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2408)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 15,
                            Body = "Magni dolorem laborum perferendis magnam.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2775),
                            IsDeleted = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 674, DateTimeKind.Local).AddTicks(2791)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(151),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(1007),
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 6,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2284),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2342),
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2487),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2501),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 6,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2569),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2752),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 10,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2877),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2886),
                            UserId = 16
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 4,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2929),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2937),
                            UserId = 12
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 3,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2977),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(2985),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3027),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3035),
                            UserId = 17
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3075),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3082),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 5,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3123),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3131),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 2,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3172),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3180),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 4,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3219),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3227),
                            UserId = 18
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3266),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3274),
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 14,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3315),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3323),
                            UserId = 10
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 18,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3363),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3371),
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3413),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3421),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3462),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3470),
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 5,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3510),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3518),
                            UserId = 21
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3557),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3565),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 2,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3604),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 714, DateTimeKind.Local).AddTicks(3611),
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 271, DateTimeKind.Local).AddTicks(3215),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/justinrhee/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(3576)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(5908),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/cboller1/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(5963)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6061),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gojeanyn/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6092)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6167),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jamiebrittain/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6180)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6234),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/terrorpixel/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6250)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6355),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/russell_baylis/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6386)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6499),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ifarafonow/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6524)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6635),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/abelcabans/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6656)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6737),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/alagoon/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6751)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6821),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/andrewcohen/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6844)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6938),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/instalox/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(6960)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7055),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dotgridline/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7070)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7128),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/marshallchen_/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7143)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7199),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/helderleal/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7213)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7303),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/orkuncaylar/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7323)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7409),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/nellleo/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7430)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7522),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rmlewisuk/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7544)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7635),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/oktayelipek/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7654)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7749),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/anjhero/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7768)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7858),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/9lessons/128.jpg",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 272, DateTimeKind.Local).AddTicks(7878)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(1590),
                            URL = "https://picsum.photos/640/480/?image=886",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(2982)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(3755),
                            URL = "https://picsum.photos/640/480/?image=1013",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(3849)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(3961),
                            URL = "https://picsum.photos/640/480/?image=644",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(3985)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4078),
                            URL = "https://picsum.photos/640/480/?image=232",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4101)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4195),
                            URL = "https://picsum.photos/640/480/?image=8",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4218)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4309),
                            URL = "https://picsum.photos/640/480/?image=350",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4328)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4424),
                            URL = "https://picsum.photos/640/480/?image=101",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4445)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4539),
                            URL = "https://picsum.photos/640/480/?image=59",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4556)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4647),
                            URL = "https://picsum.photos/640/480/?image=384",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4672)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4766),
                            URL = "https://picsum.photos/640/480/?image=1071",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4778)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4861),
                            URL = "https://picsum.photos/640/480/?image=697",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4882)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(4996),
                            URL = "https://picsum.photos/640/480/?image=318",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5021)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5113),
                            URL = "https://picsum.photos/640/480/?image=994",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5129)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5214),
                            URL = "https://picsum.photos/640/480/?image=80",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5237)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5334),
                            URL = "https://picsum.photos/640/480/?image=663",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5356)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5455),
                            URL = "https://picsum.photos/640/480/?image=75",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5474)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5569),
                            URL = "https://picsum.photos/640/480/?image=911",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5589)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5676),
                            URL = "https://picsum.photos/640/480/?image=89",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5696)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5784),
                            URL = "https://picsum.photos/640/480/?image=853",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5803)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5901),
                            URL = "https://picsum.photos/640/480/?image=681",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 289, DateTimeKind.Local).AddTicks(5922)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 18,
                            Body = "Officiis debitis odit veritatis quos tempora ut ipsum. Impedit distinctio nihil dignissimos tenetur autem itaque illo perspiciatis. Rerum assumenda sit quis quisquam dolor dolorum. Ad vero ex iste maiores reprehenderit in similique dolores iure. Ad incidunt excepturi enim praesentium ea minima natus est vel.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(2738),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(4109)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "earum",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(5669),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(5708)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 9,
                            Body = "Iure rerum officiis incidunt doloribus enim qui. Tempore aperiam accusamus iure. Unde nesciunt enim ipsam et praesentium est rerum odio et. Sit occaecati voluptatem tempora laborum soluta eligendi animi debitis. Alias consequatur in alias occaecati alias aut dolore est non.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(6504),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(6519)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 15,
                            Body = "Tempore asperiores voluptatem sint delectus nihil rerum ut accusantium quae. Quis modi ut asperiores laboriosam enim. Aut perspiciatis sequi accusamus enim repudiandae praesentium. Quidem fugiat sunt earum possimus facilis id voluptatem.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(6883),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(6895)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 8,
                            Body = "Voluptates sed inventore.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(7932),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(7955)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "Temporibus nihil et amet harum sint ut quod. Et soluta aliquid inventore magnam et fugit dolor dicta. Eum unde sapiente mollitia nemo.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(8302),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 655, DateTimeKind.Local).AddTicks(8312)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            Body = @"Esse dolores ex et maxime non.
Numquam ut nemo quo quod repellat ducimus eos consequatur vitae.
Distinctio dolores earum.
Quis nam modi neque dolorem odit enim.
Ducimus voluptatem magni magnam qui.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(93),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(141)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "Voluptatem dolores eveniet ad dolor.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(425),
                            IsDeleted = false,
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(454)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 13,
                            Body = @"Ullam dolorem neque itaque quidem unde.
Quia est rerum qui aut dolorem et fuga eos.
Laborum maxime illo eum cum deserunt impedit.
Alias quae veniam molestias numquam.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(858),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(870)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 18,
                            Body = "Aut blanditiis veniam eum quos nihil sed aut.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(972),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(982)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = @"Doloribus et sint recusandae voluptatum.
Blanditiis et dolorum incidunt qui mollitia quidem quas sunt.
Voluptatum molestias aut repellendus quia eveniet ipsum in.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1252),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1261)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "occaecati",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1363),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1372)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            Body = @"Eligendi illo harum.
Minima distinctio aut eos voluptatem iure modi.
Temporibus vero velit sapiente ea nesciunt laboriosam possimus iusto.
Explicabo atque nisi quibusdam.
Omnis itaque eveniet culpa atque.
Rem earum ducimus earum aut adipisci.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1659),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1669)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            Body = "Rerum maxime aliquid voluptatem voluptas iste voluptas. Velit modi est natus sapiente voluptatem dolore atque corporis ipsa. Quia consequatur id ea ipsam repudiandae placeat voluptatem nostrum delectus.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1959),
                            IsDeleted = false,
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(1969)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 9,
                            Body = @"Sed animi dignissimos sunt sint vel similique.
Architecto magnam repellendus eum corrupti temporibus et quo.
Consequuntur repellat doloremque cumque quia iure aperiam.
Explicabo sed aperiam sint sint.
Quia culpa autem et est eaque non quia.
Iste aut nam odit non non quaerat.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2383),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2393)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 17,
                            Body = "Praesentium excepturi hic aut voluptas non velit quod dolorem nulla.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2521),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2530)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            Body = "et",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2579),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2587)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 15,
                            Body = "quia",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2711),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2720)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 6,
                            Body = "Blanditiis voluptatum deserunt.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2790),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(2799)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 15,
                            Body = @"Corporis est nam ut ipsum nam harum dolores quis.
Et rem exercitationem optio voluptatem voluptas.
Corrupti sint qui ratione illo non culpa.
Blanditiis illo rem quis repellendus recusandae et.
Asperiores perspiciatis molestiae sed amet dignissimos hic ipsum et necessitatibus.
Ipsa vero impedit omnis blanditiis ut doloremque temporibus officia.",
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(3236),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 656, DateTimeKind.Local).AddTicks(3245)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(603),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(1954),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3539),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3591),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3727),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3755),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3870),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(3897),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4001),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4019),
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4133),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4159),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4550),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4576),
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4675),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4686),
                            UserId = 19
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4769),
                            IsLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4799),
                            UserId = 7
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4925),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(4955),
                            UserId = 16
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5029),
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5042),
                            UserId = 18
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5110),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5139),
                            UserId = 17
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5229),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5242),
                            UserId = 21
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5316),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5334),
                            UserId = 19
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5447),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5478),
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5606),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5632),
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5739),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5767),
                            UserId = 21
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5842),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5868),
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5975),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(5995),
                            UserId = 12
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(6098),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 696, DateTimeKind.Local).AddTicks(6111),
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Latitude")
                        .HasColumnType("int");

                    b.Property<int>("Longitude")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 366, DateTimeKind.Local).AddTicks(2762),
                            Email = "Carolanne.Gleichner96@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "5/uXQxhdkd8X+CtaCLZtvoherK4Tsx4KO9pyq/Am3vk=",
                            Salt = "eWcuiLpIouioblNE8pi/FKwC14pSWLrtcjmvcQJbazE=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 366, DateTimeKind.Local).AddTicks(3650),
                            UserName = "Margaret_Ledner"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 379, DateTimeKind.Local).AddTicks(455),
                            Email = "Maryam38@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "7eASSrmnCn1f2UjKWPFKK3jsZlHgEIYLwjPSvezmBH8=",
                            Salt = "D9vj85j0RZ8t4lE+TVYKHUqCqgB1wR5mrmE7BgEaugI=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 379, DateTimeKind.Local).AddTicks(563),
                            UserName = "Saige.Considine"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 390, DateTimeKind.Local).AddTicks(9593),
                            Email = "Gerardo88@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "ltzTlNrxkFdfhslKoQg3xiatIj73mw8StFCBB7qO6TU=",
                            Salt = "PqY9e2NpWHpbD1601TiufnhTBETv2n8DIWWpdlJzf7E=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 390, DateTimeKind.Local).AddTicks(9655),
                            UserName = "Julio_Moen"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 402, DateTimeKind.Local).AddTicks(6105),
                            Email = "Anika68@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "jkntrdMusY4DSSLeepp/j310rElTmD3EFWGknx5SOq0=",
                            Salt = "30MddVZhjnELYYRpdbQPt9oB6NIItY2SBdVfFYR5whA=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 402, DateTimeKind.Local).AddTicks(6121),
                            UserName = "Delilah_Leuschke"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 414, DateTimeKind.Local).AddTicks(5810),
                            Email = "Matilde.Rosenbaum90@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "fe/QrHo6diIuHnXctSXtOjmpH9OiecrEA4vZ0EL9mVw=",
                            Salt = "3rL+l0ToTptDGGrvPsiFk7bhohmjdWFLQEcl7MVRapg=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 414, DateTimeKind.Local).AddTicks(5865),
                            UserName = "Leonor31"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 426, DateTimeKind.Local).AddTicks(4882),
                            Email = "Marianne_Kuhic@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "xRE6ElOBuSrSu5PhGh9NKtEZvdBT1JKKFD2Qlsvq/Uo=",
                            Salt = "Xph2Dob5SxeInkWOqX2BcwvqVupv4caE9Wowb9mOOMQ=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 426, DateTimeKind.Local).AddTicks(4933),
                            UserName = "Melody_Blanda"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 438, DateTimeKind.Local).AddTicks(7294),
                            Email = "Winfield93@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "voTZaHTv1kRXhu+ztCX0yJmZuhj/wNBBvrpEyHnrs/s=",
                            Salt = "U0R62kCpy88n8vFCymNvg049DP79Km/GJtUwiGGT6HY=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 438, DateTimeKind.Local).AddTicks(7350),
                            UserName = "Antonina.Green"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 450, DateTimeKind.Local).AddTicks(3741),
                            Email = "Terrell55@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "5WjBLp41xEHdEvIOixJVTdfj6Y0cN+AFlRmMyRGItwU=",
                            Salt = "AGcydNJ7H6DHDbyGA6fwcA7YYNGilV0frM+7eMKgixc=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 450, DateTimeKind.Local).AddTicks(3763),
                            UserName = "Maribel_Renner"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 462, DateTimeKind.Local).AddTicks(6213),
                            Email = "Justine_Larson@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "ihC1awEaY+2K49BlxHlZDNdc7h5iFQ/V9tUivJlENcI=",
                            Salt = "s/zlxoOWXrveNZwefw2LY97bHU8EsGFf08UwiA3TYgI=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 462, DateTimeKind.Local).AddTicks(6267),
                            UserName = "Eryn66"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 474, DateTimeKind.Local).AddTicks(6883),
                            Email = "Sigmund25@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "9K0uljdQgPL1F2t6OCZJQqsMqaz/LJDpAVvtDy05Ejo=",
                            Salt = "gCPNMKq3B8upYasJt4dtKygaONuTkhfRA1ELEnfDCig=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 474, DateTimeKind.Local).AddTicks(6937),
                            UserName = "Deja.Armstrong"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 486, DateTimeKind.Local).AddTicks(3389),
                            Email = "Ralph_Altenwerth@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "u6G4qRlX+pvm5Xd3DNCwj9pw8yuG6dbiAPlg/WKoiPI=",
                            Salt = "rWNwfFqVS43NsqA8No6D2jglkR77n85ammkaoKXIufA=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 486, DateTimeKind.Local).AddTicks(3407),
                            UserName = "Gregorio.Bayer"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 498, DateTimeKind.Local).AddTicks(2439),
                            Email = "Lyla62@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "403krANcNm0CBi28Hoqk5WekIc93UL2D+KvXhHB8NqY=",
                            Salt = "BYvoj0QA5QjBvvchv++l9BLjOZE2gUDI6H9iPHHsdLo=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 498, DateTimeKind.Local).AddTicks(2489),
                            UserName = "Olin84"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 510, DateTimeKind.Local).AddTicks(3898),
                            Email = "Jermain_Schultz@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "vbzoNnsOXioY++QXdkKQ1IPkWth1/7K5RR4E7X0Vt+Y=",
                            Salt = "qXa2s1Z1+R+vBHs2L2T++Wrd6NjpTEn1r63vfI/aWtI=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 510, DateTimeKind.Local).AddTicks(3964),
                            UserName = "Delmer.Tromp80"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 523, DateTimeKind.Local).AddTicks(3875),
                            Email = "Katelynn_Rice@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "TpqCTYpWeIfRCGD+txM+7T1raPl2wXz8L7fvMp6ha7o=",
                            Salt = "9Kc4DBFX2ZAtvPdCrbN4vxtytdkFd0Ep9heCJavz1KU=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 523, DateTimeKind.Local).AddTicks(4442),
                            UserName = "Jordan.VonRueden50"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 536, DateTimeKind.Local).AddTicks(4390),
                            Email = "Rodrigo_Pollich@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "P5vdNQFLQXZkVMji46JO1hQDYGwDNVcB6ZYTIG8pAhU=",
                            Salt = "Z3d7y5n1wlpDSk6nM+yxP4/EIJECE0wOVNVtXm6k6aY=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 536, DateTimeKind.Local).AddTicks(4942),
                            UserName = "Rhiannon.Baumbach99"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 548, DateTimeKind.Local).AddTicks(9537),
                            Email = "Myrna.Towne55@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "HtVNu2NRoaHObBI8xM+S4l4RG3xlVIoZwqRmmDh6K3U=",
                            Salt = "ybFYX6kyj3duHeXo9Mr+O1lL9P/9kIUteyl+zW/skIo=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 548, DateTimeKind.Local).AddTicks(9963),
                            UserName = "Richie_McCullough"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 560, DateTimeKind.Local).AddTicks(8785),
                            Email = "Justina.Stokes91@yahoo.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "LERgRZm/hpDOmJCHQ5YsGD0SMTEMdZ3wJwf61iWGg6w=",
                            Salt = "EnAfuItTl85F9WvOqPbrtk8vW4mlbaLOLDmbHpTo64c=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 560, DateTimeKind.Local).AddTicks(8853),
                            UserName = "Coby_Hamill"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 576, DateTimeKind.Local).AddTicks(1533),
                            Email = "Rick.Prohaska@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "Td3H8AIF/u2VCHPmqf2gAr3FdBYb+nTpYtCPjaJr9Io=",
                            Salt = "QWu2I7MqU5n1C1IRNKDgsudquBUyA9mG1iEpqFb1AOQ=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 576, DateTimeKind.Local).AddTicks(1651),
                            UserName = "Layne.Senger83"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 598, DateTimeKind.Local).AddTicks(9997),
                            Email = "Dane_Harris80@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "YqPJ1EyZhoD+Q9a6wGvb2Qixqx1VqRugE8baos6DGOg=",
                            Salt = "KupJ1fqj8mndzQ8mNW+bWZPieWjDf5tbNqUaMIUpFfM=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 599, DateTimeKind.Local).AddTicks(104),
                            UserName = "Ryleigh.Hettinger27"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 616, DateTimeKind.Local).AddTicks(4979),
                            Email = "Alexandrea.Hammes@hotmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "lP6X+h00VetXrbjwGJbSEskDfey+OPsn8Cx6HqnqL9w=",
                            Salt = "Oe3XKeciBJJzoJhH7oAkXpdnLQIUiAVUYYi98u8edEM=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 616, DateTimeKind.Local).AddTicks(5074),
                            UserName = "Guy.Murray"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 632, DateTimeKind.Local).AddTicks(7578),
                            Email = "test@gmail.com",
                            Latitude = 0,
                            Longitude = 0,
                            Password = "5vCiXXoH0QhK0hwuQ9R+ZuVmOgylfbFiUON1qon8NBw=",
                            Salt = "nFTK7ZtDoeYdgXsyou2fLLx+1dYCpTIDzc/wCtLUd7w=",
                            UpdatedAt = new DateTime(2020, 9, 20, 10, 50, 40, 632, DateTimeKind.Local).AddTicks(7578),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
