// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20200614064835_Add_Field_IsDeleted")]
    partial class Add_Field_IsDeleted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 5,
                            Body = "Aut sed eius accusamus.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(1923),
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(2838)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 11,
                            Body = "Doloribus est quibusdam.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(3842),
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(3883)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 12,
                            Body = "Laudantium odit corrupti sit ea vel.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4224),
                            PostId = 16,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4257)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Body = "Ut quis id eum velit nihil quia.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4552),
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4570)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            Body = "Qui fuga molestiae molestias perferendis quos.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4716),
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(4744)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 21,
                            Body = "Quos placeat magni omnis reprehenderit iusto vero asperiores illum impedit.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5217),
                            PostId = 15,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5247)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 19,
                            Body = "Qui occaecati ut pariatur voluptatem illum ut eligendi.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5427),
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5436)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 10,
                            Body = "Sit quaerat assumenda aperiam animi.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5517),
                            PostId = 14,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5524)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 18,
                            Body = "Delectus laborum ut.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5588),
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5595)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 16,
                            Body = "Numquam hic nisi et corporis reprehenderit iste.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5678),
                            PostId = 2,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5686)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            Body = "Et labore dolorem incidunt.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5752),
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5760)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 14,
                            Body = "Fuga dolorem debitis possimus dolores.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5827),
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(5835)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Nisi voluptatem sint facere perferendis sit.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6021),
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6029)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            Body = "Ab et molestiae quaerat natus.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6103),
                            PostId = 14,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6111)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 10,
                            Body = "Nesciunt deserunt consequuntur ea nemo.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6182),
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6190)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Body = "Aliquid rerum nam quaerat fugiat beatae.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6266),
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6274)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            Body = "Sapiente quis rerum.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6339),
                            PostId = 2,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6347)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 11,
                            Body = "Eius aut et dolor et et alias et aut sit.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6441),
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 12,
                            Body = "Optio eaque aperiam.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6508),
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6516)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 21,
                            Body = "Nam ut voluptatem accusamus nihil.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6680),
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 43, DateTimeKind.Local).AddTicks(6689)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(8279),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9008),
                            UserId = 14
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9706),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9734),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9793),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9801),
                            UserId = 18
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9839),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9847),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9881),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9888),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9925),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9933),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9968),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 61, DateTimeKind.Local).AddTicks(9976),
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(9),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(16),
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 8,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(52),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(59),
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(93),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(101),
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(134),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(142),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(278),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(287),
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(327),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(335),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(370),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(377),
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(411),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(419),
                            UserId = 16
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(452),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(459),
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(492),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(500),
                            UserId = 14
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(533),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(540),
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(574),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(582),
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(615),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 62, DateTimeKind.Local).AddTicks(623),
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(3075),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/twittypork/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(8375)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9303),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/geobikas/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9345)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9393),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/webtanya/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9401)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9431),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/joe_black/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9439)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9468),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gusoto/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9475)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9505),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ryhanhassan/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9513)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9543),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/cdavis565/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9580),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/otozk/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9587)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9616),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/matbeedotcom/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9624)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9653),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/yecidsm/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9660)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9689),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/markwienands/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9696)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9726),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/pmeissner/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9734)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9761),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/zforrester/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9768)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9797),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/praveen_vijaya/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9804)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9833),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/bartjo/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9840)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9869),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/baluli/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9876)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9906),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/runningskull/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9913)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9941),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jennyyo/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9949)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9978),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/marclgonzales/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 704, DateTimeKind.Local).AddTicks(9985)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 705, DateTimeKind.Local).AddTicks(12),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/marcusgorillius/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 705, DateTimeKind.Local).AddTicks(19)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(6976),
                            URL = "https://picsum.photos/640/480/?image=382",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(7904)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8256),
                            URL = "https://picsum.photos/640/480/?image=279",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8299)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8342),
                            URL = "https://picsum.photos/640/480/?image=47",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8351)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8384),
                            URL = "https://picsum.photos/640/480/?image=387",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8392)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8421),
                            URL = "https://picsum.photos/640/480/?image=35",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8429)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8459),
                            URL = "https://picsum.photos/640/480/?image=504",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8466)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8497),
                            URL = "https://picsum.photos/640/480/?image=245",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8504)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8535),
                            URL = "https://picsum.photos/640/480/?image=10",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8543)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8596),
                            URL = "https://picsum.photos/640/480/?image=164",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8603)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8634),
                            URL = "https://picsum.photos/640/480/?image=57",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8641)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8670),
                            URL = "https://picsum.photos/640/480/?image=215",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8678)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8707),
                            URL = "https://picsum.photos/640/480/?image=934",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8714)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8743),
                            URL = "https://picsum.photos/640/480/?image=172",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8750)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8780),
                            URL = "https://picsum.photos/640/480/?image=336",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8787)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8818),
                            URL = "https://picsum.photos/640/480/?image=917",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8825)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8855),
                            URL = "https://picsum.photos/640/480/?image=647",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8862)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8891),
                            URL = "https://picsum.photos/640/480/?image=411",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8898)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8928),
                            URL = "https://picsum.photos/640/480/?image=528",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8936)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8965),
                            URL = "https://picsum.photos/640/480/?image=607",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(8972)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(9001),
                            URL = "https://picsum.photos/640/480/?image=106",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 711, DateTimeKind.Local).AddTicks(9009)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 17,
                            Body = @"Quia libero sit dicta modi molestias qui.
Voluptatem aut omnis ut qui modi natus voluptas nemo.
Occaecati et labore neque quo minima consequuntur molestiae est nulla.
Facere et placeat explicabo fugit voluptates ut dolore.
Quidem nisi qui voluptate ipsa dignissimos in dolor.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(4898),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(5710)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Body = "Nesciunt velit perferendis magni.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(7802),
                            IsDeleted = false,
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(7843)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 8,
                            Body = "Quibusdam id exercitationem magni molestias aut perferendis aliquam laborum enim. Beatae qui ullam. Fugiat fugiat quia enim.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(9529),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(9554)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 18,
                            Body = "Error et mollitia dolores id delectus quo et officia velit.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(9698),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 33, DateTimeKind.Local).AddTicks(9707)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 18,
                            Body = @"Provident laboriosam error non perspiciatis.
Voluptatem quia sunt fugit quo exercitationem.
Et soluta ut et cupiditate possimus.
Optio voluptates id ad nostrum est ducimus et.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(26),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(36)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 7,
                            Body = "Corporis iste officia non eos vel qui.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(133),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(141)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 20,
                            Body = "Eum eveniet libero.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(212),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(220)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Body = "Ipsam pariatur quibusdam culpa. Minus quis labore assumenda doloremque eum et. Et ut asperiores necessitatibus sit placeat quia et quibusdam. Molestiae iure necessitatibus modi vel. Vel quas non doloremque tempore qui porro. Aut delectus velit pariatur in a rem.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(588),
                            IsDeleted = false,
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(597)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            Body = "Harum tempore quas laborum sequi facilis nisi sint.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(857),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(867)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Body = "minus",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1317),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1336)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = @"Ullam non vitae excepturi unde corrupti sint.
Omnis ea tempora quo dolor.
Voluptatem dolorum dolores maxime rerum officiis necessitatibus autem iure voluptas.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1557),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1566)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 15,
                            Body = "omnis",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1618),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(1626)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 19,
                            Body = "Rerum quia vero amet eius vitae amet. Dolore animi veniam sed soluta illum quam. Fugit sit neque libero sint quidem molestiae dolorem facere rerum. Aliquid eos dolores et quam ut. Fugiat omnis praesentium et ad. Omnis quis facilis omnis aut non rerum corporis.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2050),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2059)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            Body = "libero",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2108),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2117)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "enim",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2263),
                            IsDeleted = false,
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2272)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 18,
                            Body = "Expedita fugiat qui fugit minus.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2351),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2360)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 20,
                            Body = "Facilis quam nobis quod et voluptates tempora doloribus voluptatem est.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2462),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2470)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Body = "quidem",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2519),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2526)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            Body = "facilis",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2574),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2582)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            Body = @"Repellat earum consequatur molestiae quo non.
Ut ea provident.
Quasi deleniti iusto non ad.
Dolorem voluptatem aut nemo saepe qui.",
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2879),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 34, DateTimeKind.Local).AddTicks(2887)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(2182),
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(2907),
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3714),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3739),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3799),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3807),
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3844),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3852),
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3889),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3897),
                            UserId = 16
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3933),
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3941),
                            UserId = 15
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3978),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(3986),
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4018),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4025),
                            UserId = 21
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4062),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4069),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4102),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4110),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4142),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4150),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4284),
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4293),
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4329),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4337),
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4371),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4378),
                            UserId = 19
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4411),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4419),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4452),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4459),
                            UserId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4490),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4498),
                            UserId = 21
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4530),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4537),
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4570),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4578),
                            UserId = 13
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4614),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 53, DateTimeKind.Local).AddTicks(4622),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 770, DateTimeKind.Local).AddTicks(6538),
                            Email = "Lola.Monahan@hotmail.com",
                            Password = "Ix71rHBhqii3MApn43pOKnf3J8EhwYXXmQyklv6cV9E=",
                            Salt = "Jeb2szGhDbCqaGIdohjXh7SnVxj8iK943Uwq8tbxt0A=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 770, DateTimeKind.Local).AddTicks(7359),
                            UserName = "Chyna.Littel"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 782, DateTimeKind.Local).AddTicks(6404),
                            Email = "Maye.Schinner@hotmail.com",
                            Password = "YZeWypO9e+qnSv2y2y9VEJz/Oxd10PzoeEwZJo04Evk=",
                            Salt = "4gdwLKBEgjm73oITMHaom9q0/iQ6Mg215oaRqtg8FMM=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 782, DateTimeKind.Local).AddTicks(6450),
                            UserName = "Rupert_Paucek60"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 794, DateTimeKind.Local).AddTicks(5435),
                            Email = "Emery_Harris@gmail.com",
                            Password = "vU4HRf9zUQWwV6dxihB7ASgUxyWmoGQMbq1W4dlThI0=",
                            Salt = "gaUwfPXqg/gAwNOPDmdQ5inFWA9pkprjzXX/SUaa1no=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 794, DateTimeKind.Local).AddTicks(5493),
                            UserName = "Theodora_Spencer18"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 806, DateTimeKind.Local).AddTicks(3686),
                            Email = "Emmett59@hotmail.com",
                            Password = "AIpieYWVUGcKybGwt7Lyki3QigKCMr6woVqB3GFW+yc=",
                            Salt = "fo77/2EObZiNfYxc2wXC/u7sQ61XwM5bLgFzvSfL9l4=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 806, DateTimeKind.Local).AddTicks(3732),
                            UserName = "Rosa68"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 818, DateTimeKind.Local).AddTicks(465),
                            Email = "Sid.Hegmann64@yahoo.com",
                            Password = "EQp6YebK4DZj8qlB8WvbXBI2OFdYZqwRBq1jm/wBzPk=",
                            Salt = "hz+Bceh9/kxvWjbn2A4AiRXFK9/GPqqr7FxCwtuiWdg=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 818, DateTimeKind.Local).AddTicks(487),
                            UserName = "Jake.MacGyver95"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 830, DateTimeKind.Local).AddTicks(81),
                            Email = "Godfrey_Larkin99@hotmail.com",
                            Password = "Dsk9J/2EwkXpj94FecFoh76QRrcc1c9cEMcEr8zTMeo=",
                            Salt = "a09aavhDYtiwm9KFzxi/P8+ODV1cCz5T3m8/u6+jgRw=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 830, DateTimeKind.Local).AddTicks(144),
                            UserName = "Reilly_Bode"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 841, DateTimeKind.Local).AddTicks(8960),
                            Email = "Ethel.Keeling73@gmail.com",
                            Password = "Vp9mgy2aav9E3Pxelu/EoVl1h4AeJwoou/tQOb+slwg=",
                            Salt = "NfjJqgVkvxum7gfI2Vs1avDCm+wgdib1w80N49nhDbc=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 841, DateTimeKind.Local).AddTicks(9016),
                            UserName = "Jovan64"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 855, DateTimeKind.Local).AddTicks(6885),
                            Email = "Breana1@hotmail.com",
                            Password = "M99mxX8IUtZBQq/vZDDDpfoPCo3sz4CmIC0YPV5KkSY=",
                            Salt = "6pLNXUWviO+xfH7CNtSNZV0I0/b1oWnYDZ2MSUuD9Uk=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 855, DateTimeKind.Local).AddTicks(6981),
                            UserName = "Napoleon74"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 873, DateTimeKind.Local).AddTicks(9889),
                            Email = "Lane_Breitenberg18@yahoo.com",
                            Password = "k0I2VTAtSZpvQX8P3mnUyjvZpYD8Z/aSO+9aO3D87Uk=",
                            Salt = "JGfIj1ikMirm91ySrCd/yZDzWIIhl4yF9eB+iMr3VlE=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 873, DateTimeKind.Local).AddTicks(9957),
                            UserName = "Hassan98"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 888, DateTimeKind.Local).AddTicks(8475),
                            Email = "Arthur33@gmail.com",
                            Password = "0QanDLzv1EXrUn/3/h8PUybLM4rS24NsDhPf81hsQ3c=",
                            Salt = "GcbeQhjJhLfIsHG+ZzpwMw5PMiOhuNO3qUCMTucdOOI=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 888, DateTimeKind.Local).AddTicks(8526),
                            UserName = "Pattie80"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 900, DateTimeKind.Local).AddTicks(6539),
                            Email = "Claire.Ziemann@yahoo.com",
                            Password = "DVlQsHxBOxdNfrZzljuviFm5ZPIbFbXiKMI7z273eG8=",
                            Salt = "VwBHS0aY0QWy/O0jpHuFp7FsOVBN3uIL8gYLOQJxXVg=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 900, DateTimeKind.Local).AddTicks(6587),
                            UserName = "Aniyah.Schroeder"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 912, DateTimeKind.Local).AddTicks(3646),
                            Email = "Vernon55@gmail.com",
                            Password = "2BwnTwWdy+G2g2IaQSP5UjrmAKCYMj6Ws2/Z9M42uww=",
                            Salt = "dJJwv+z6z9KWw3dBAJz16zL/oyTcXYN4rZPJudBIFqw=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 912, DateTimeKind.Local).AddTicks(3671),
                            UserName = "Dahlia.Nienow52"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 924, DateTimeKind.Local).AddTicks(1668),
                            Email = "Sophie39@gmail.com",
                            Password = "x0VUAWV5E/tE6K3zg93EobhUMDkAeuMD0QBD/KU7i4A=",
                            Salt = "jXYMo6bl+2hv6raeR2MqogGBA98VpeU/ndBDYE2DzUE=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 924, DateTimeKind.Local).AddTicks(1706),
                            UserName = "Markus81"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 936, DateTimeKind.Local).AddTicks(1290),
                            Email = "Stephania_Sporer25@gmail.com",
                            Password = "EeHsEmc0oHYkjFAWaITJ4RNSICHjiLn6sx+eGdwDXMQ=",
                            Salt = "tIosapqlBQq3HOiuwLWCUgvYD0He8gy98aHB36rKEnU=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 936, DateTimeKind.Local).AddTicks(1355),
                            UserName = "Martina.Brown93"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 948, DateTimeKind.Local).AddTicks(592),
                            Email = "Alexa_Stamm34@hotmail.com",
                            Password = "EtpVp1pEAG6cYM/Fad1Ohbl00MK5oMK5eF1YP5pcL70=",
                            Salt = "O4JKnylRLLUrsWdxImemRHsFU0K2jARLjzh7VxA4e8I=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 948, DateTimeKind.Local).AddTicks(631),
                            UserName = "Lennie_Friesen40"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 959, DateTimeKind.Local).AddTicks(7828),
                            Email = "Michel.Roob@gmail.com",
                            Password = "HJvznc7pMRar2fJHArmN+nvOgAFRu40QaO4HNm/sWIA=",
                            Salt = "Ogw9Qbv/UXy/TYh8l/vx3uCOgsi+pQaN6i0QK0tcwLc=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 959, DateTimeKind.Local).AddTicks(7864),
                            UserName = "Mallie.Powlowski"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 971, DateTimeKind.Local).AddTicks(5438),
                            Email = "Brayan64@yahoo.com",
                            Password = "VltzWOaT6v34UB31O827cbW7FPhyi+xDgH6aBVfNghk=",
                            Salt = "W06809DFHBhNEntcsPC7XUtA+OWjr2I+X73RXGH1evQ=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 971, DateTimeKind.Local).AddTicks(5473),
                            UserName = "Tierra_Ratke8"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 983, DateTimeKind.Local).AddTicks(2831),
                            Email = "Clifford_Gorczany@yahoo.com",
                            Password = "euZvW1lcmlm+/ibJaD1Gi7TJSroaOGNvVZhoRE52f/4=",
                            Salt = "5aA9cqa/RXNNQ7gAvixR/mTtQW3o7GkoaSU6+eqrDXI=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 983, DateTimeKind.Local).AddTicks(2864),
                            UserName = "Brendon_Gusikowski"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 995, DateTimeKind.Local).AddTicks(9858),
                            Email = "Evelyn83@hotmail.com",
                            Password = "RUk34isxHegXDsOKixDjvEcahujTj22JZ2Gd0x6QwZI=",
                            Salt = "quKfhPUXBI0iVZm55kRxOup9cVs3TuQswNJv9YrzV/A=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 33, 996, DateTimeKind.Local).AddTicks(437),
                            UserName = "Talon_Jacobs83"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 9, DateTimeKind.Local).AddTicks(1606),
                            Email = "Cassie28@hotmail.com",
                            Password = "mko9POpA8ESHrQ+h/Fu8S+fZ6oCSpAQjvnZUuZFAZ9k=",
                            Salt = "xDypz2DGRbKpEPa0gyAYgVmsKbxPwTWtbHW5V9au7MQ=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 9, DateTimeKind.Local).AddTicks(2139),
                            UserName = "Lily78"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 21, DateTimeKind.Local).AddTicks(1329),
                            Email = "test@gmail.com",
                            Password = "BCnRt2/aUfmIFiWuHb3DW/nHu4vHX67DuxwVFX6meRU=",
                            Salt = "AgYQ/EUJI1k7ZgY1Ov9YnYeoO+c3yR+PvYtUz3Th1H4=",
                            UpdatedAt = new DateTime(2020, 6, 14, 9, 48, 34, 21, DateTimeKind.Local).AddTicks(1329),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
