// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    partial class ThreadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Body = "Voluptate sunt esse sint dolor id consequatur non.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(3202),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(4020)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 18,
                            Body = "Earum vel dicta ipsam rerum.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(4941),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5030)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 7,
                            Body = "Sunt id minus esse quas quisquam facilis.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5176),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5187)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 20,
                            Body = "Iure sapiente repellendus tempore voluptatibus repudiandae velit sit.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5299),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5310)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 18,
                            Body = "Dolore sit velit magnam at.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5397),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5407)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            Body = "Eligendi corrupti quaerat assumenda magni blanditiis molestiae cum cum voluptates.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5626),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5637)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            Body = "Ea unde est omnis voluptatum.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5725),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5735)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 6,
                            Body = "Fugit et eveniet voluptatibus.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5809),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5818)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 6,
                            Body = "Provident dolorem et debitis rem enim.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5906),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5915)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Adipisci expedita eius inventore.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5987),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(5996)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 15,
                            Body = "Quod in maiores voluptas dolor omnis.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6079),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6088)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 13,
                            Body = "Nisi aut culpa officiis ea temporibus aut.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6178),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6187)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            Body = "Excepturi quaerat quia nam.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6342),
                            IsDeleted = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6351)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            Body = "Sint ea qui quae omnis recusandae.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6441),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 21,
                            Body = "Qui voluptatem alias fuga.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6526),
                            IsDeleted = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6535)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 17,
                            Body = "Ullam consequuntur quas est ullam.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6611),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6620)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Body = "Est ut explicabo aut neque quam minus voluptatibus cumque.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6749),
                            IsDeleted = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 15,
                            Body = "Iste provident similique officiis maiores.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6838),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6847)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Body = "Dolorum est necessitatibus neque.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(6995),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(7005)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Body = "Sed dolores qui.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(7077),
                            IsDeleted = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 252, DateTimeKind.Local).AddTicks(7085)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(147),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(913),
                            UserId = 18
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1664),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1689),
                            UserId = 17
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1752),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1762),
                            UserId = 14
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1809),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1818),
                            UserId = 15
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1862),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1871),
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1914),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1922),
                            UserId = 18
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1967),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(1976),
                            UserId = 21
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2022),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2030),
                            UserId = 20
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2077),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2085),
                            UserId = 14
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2233),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2243),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2282),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2291),
                            UserId = 14
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2328),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2335),
                            UserId = 17
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2372),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2380),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2417),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2425),
                            UserId = 17
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2466),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2474),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2513),
                            IsLike = false,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2521),
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2558),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2566),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2602),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2610),
                            UserId = 16
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2645),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2653),
                            UserId = 12
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2690),
                            IsLike = true,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 271, DateTimeKind.Local).AddTicks(2698),
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(1103),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sovesove/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(6392)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7329),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sdidonato/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7368)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7421),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7431)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7464),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/smaczny/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7472)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7504),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/evandrix/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7512)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7544),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/overcloacked/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7551)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7583),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/bcrad/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7590)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7622),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ariffsetiawan/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7630)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7661),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/themadray/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7668)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7701),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/nerdgr8/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7709)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7740),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/HenryHoffman/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7748)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7779),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7787)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7817),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/charliecwaite/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7825)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7856),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rehatkathuria/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7863)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7894),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/pechkinator/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7902)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7931),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mbilderbach/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7939)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7969),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/zackeeler/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(7977)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8008),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/helderleal/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8015)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8046),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/hugomano/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8053)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8085),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/chaabane_wail/128.jpg",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 921, DateTimeKind.Local).AddTicks(8092)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(4901),
                            URL = "https://picsum.photos/640/480/?image=329",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(5653)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(5993),
                            URL = "https://picsum.photos/640/480/?image=398",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6035)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6076),
                            URL = "https://picsum.photos/640/480/?image=653",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6084)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6116),
                            URL = "https://picsum.photos/640/480/?image=356",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6124)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6154),
                            URL = "https://picsum.photos/640/480/?image=250",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6162)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6192),
                            URL = "https://picsum.photos/640/480/?image=919",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6200)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6230),
                            URL = "https://picsum.photos/640/480/?image=869",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6237)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6266),
                            URL = "https://picsum.photos/640/480/?image=350",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6274)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6303),
                            URL = "https://picsum.photos/640/480/?image=76",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6311)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6407),
                            URL = "https://picsum.photos/640/480/?image=259",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6416)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6449),
                            URL = "https://picsum.photos/640/480/?image=70",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6457)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6487),
                            URL = "https://picsum.photos/640/480/?image=165",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6495)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6523),
                            URL = "https://picsum.photos/640/480/?image=111",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6531)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6559),
                            URL = "https://picsum.photos/640/480/?image=306",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6567)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6596),
                            URL = "https://picsum.photos/640/480/?image=950",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6603)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6633),
                            URL = "https://picsum.photos/640/480/?image=7",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6640)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6669),
                            URL = "https://picsum.photos/640/480/?image=539",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6676)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6706),
                            URL = "https://picsum.photos/640/480/?image=16",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6713)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6744),
                            URL = "https://picsum.photos/640/480/?image=465",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6751)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6780),
                            URL = "https://picsum.photos/640/480/?image=570",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 928, DateTimeKind.Local).AddTicks(6787)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 13,
                            Body = "Quo quia dicta accusantium.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(1364),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(2174)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 6,
                            Body = "autem",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(3467),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(3506)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 20,
                            Body = @"Accusamus omnis voluptas voluptates perspiciatis doloremque unde.
Odit asperiores ut ea ut ipsa facilis architecto doloremque.
Excepturi ut est veritatis molestiae consectetur nam asperiores.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(7911),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(7945)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 6,
                            Body = "Qui provident sunt odio quam.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8079),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8089)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 20,
                            Body = "voluptatem",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8143),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8152)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "Sit unde libero assumenda unde occaecati ullam nihil.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8255),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 242, DateTimeKind.Local).AddTicks(8264)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 20,
                            Body = "Pariatur sunt et unde vel et nostrum at voluptatem. Repellendus aspernatur fuga. Vel voluptates deleniti rerum harum enim sit quod. Repellat tempora tempore in neque perspiciatis odit eum. Fuga laborum nesciunt est debitis animi illum minima. Debitis sint ut aut.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(84),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(109)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "Eos voluptatem adipisci quas voluptatum odit non et voluptatem. Incidunt consequuntur nemo nesciunt. Eaque voluptatum aut rem quia aperiam aut. Aliquid eos qui.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(448),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(460)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 11,
                            Body = "natus",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(516),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(524)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 8,
                            Body = @"Sed omnis sed eos illo omnis harum veniam cum quae.
Sunt omnis repudiandae.
Consectetur repudiandae esse consequatur omnis quaerat velit nulla consequatur.
Veniam dolorem consequuntur.
Reprehenderit quisquam qui iste consectetur quas corrupti ea officiis.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(892),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(903)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 18,
                            Body = "Reprehenderit corporis sunt aut veritatis consectetur enim.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1002),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1011)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 15,
                            Body = "nemo",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1141),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1150)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 20,
                            Body = "Fugit assumenda itaque quas occaecati veniam voluptas mollitia perferendis. Velit ea fugiat eaque asperiores consequatur commodi. Consequatur ut ad qui eius quidem vero iure. Fuga qui similique corrupti qui dolor id. Et nihil saepe architecto odit reiciendis quos et dolores.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1556),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1566)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 17,
                            Body = @"Corporis fuga ipsa.
Dolorem voluptatum ut.
Corporis est dolores qui nihil blanditiis dignissimos.
Dolorem culpa tempora.
Nisi culpa totam officia cumque.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1784),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1794)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            Body = "Vero rerum at possimus cupiditate quo earum dignissimos.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1968),
                            IsDeleted = false,
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(1977)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Body = "temporibus",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2033),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2041)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "earum",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2089),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2098)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 21,
                            Body = "quam",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2146),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2154)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 13,
                            Body = "Cupiditate possimus quisquam nesciunt blanditiis.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2235),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2244)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 12,
                            Body = @"Ducimus cumque minima ut dolor dolorum quas quidem aliquid.
Aspernatur atque et praesentium eius facilis quia nostrum placeat vero.
Ut laborum ut ut voluptas.
Dolor doloribus veritatis.
Iusto aspernatur minima.",
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2662),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 243, DateTimeKind.Local).AddTicks(2674)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(1614),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(2476),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3332),
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3356),
                            UserId = 18
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3415),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3424),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3464),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3472),
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3511),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3519),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3555),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3563),
                            UserId = 12
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3598),
                            IsLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3606),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3647),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3655),
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3695),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3703),
                            UserId = 20
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3821),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3830),
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3868),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3875),
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3911),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3918),
                            UserId = 8
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3953),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3961),
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(3998),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4005),
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4040),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4048),
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4085),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4093),
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4128),
                            IsLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4136),
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4171),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4179),
                            UserId = 16
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4213),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4221),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4256),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 262, DateTimeKind.Local).AddTicks(4264),
                            UserId = 13
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 983, DateTimeKind.Local).AddTicks(7892),
                            Email = "Ramiro_Beer@gmail.com",
                            Password = "D3h0sPyz3BEfMYVuvwr+6yFV0GzrKCRQNm/5wlgMx1s=",
                            Salt = "GxNRzNFfJqyjOc1mJhmtlR4Kg3lnxHiNg90KsxkGYxI=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 983, DateTimeKind.Local).AddTicks(8707),
                            UserName = "Wilhelm.Rosenbaum49"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 996, DateTimeKind.Local).AddTicks(1046),
                            Email = "Mitchel_Bayer@hotmail.com",
                            Password = "EjmDnNNb1XptrLzXiGhpXy7bUbAO+qlC1s2fO4b+878=",
                            Salt = "Wq98KgrD6bGh6XLj4X/2aazDjZ98sKfw1zrMl0IxfDk=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 44, 996, DateTimeKind.Local).AddTicks(1150),
                            UserName = "Chris.Stanton"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 10, DateTimeKind.Local).AddTicks(5432),
                            Email = "Yessenia_Klein@gmail.com",
                            Password = "A8teFnOxMmz6CF0oSrY0xWk70koxD9Ck5QppsGlxFuA=",
                            Salt = "TKegl0+6hvmAs4e+Un/nEuXYJfiOJXZoM23/Ed65kHM=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 10, DateTimeKind.Local).AddTicks(5496),
                            UserName = "Blaze.OReilly"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 22, DateTimeKind.Local).AddTicks(2360),
                            Email = "Jade.Balistreri@yahoo.com",
                            Password = "V5Ya/pOQ+nqaZjCLrhd3om+tGICUKhyeFXoOxZd5EHQ=",
                            Salt = "SQRDPQEiJD9orCPXK+tVwf9MGLOPZai3c2QYqCPd0AM=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 22, DateTimeKind.Local).AddTicks(2392),
                            UserName = "Leda51"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 34, DateTimeKind.Local).AddTicks(100),
                            Email = "Eli_Turcotte@hotmail.com",
                            Password = "1bSNYvHThGgxkpWJMRbd56hzf4uARwr7ernndalR4tE=",
                            Salt = "Of1mKice+yHlcb2jwA5zlMJdYjVXt8C5jP3oOnAH9+U=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 34, DateTimeKind.Local).AddTicks(155),
                            UserName = "Sidney4"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 46, DateTimeKind.Local).AddTicks(1328),
                            Email = "Ernesto.Kub@yahoo.com",
                            Password = "Oc2wIJClYHEoI07vyVVH0atADpda/TAn7/8a3k4kS6M=",
                            Salt = "7P9waCiihX5ktkl4G/R+6DbLfuL2H6lbo6+/4rcgLZM=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 46, DateTimeKind.Local).AddTicks(1364),
                            UserName = "Hope38"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 58, DateTimeKind.Local).AddTicks(9226),
                            Email = "Jamarcus_Runolfsson@hotmail.com",
                            Password = "/tETWDlqRpGgZyq0TLIyjMHwUAmx2l1ccZvhIiOEQVg=",
                            Salt = "4g+x+0IGaUse5JjalBxAiP1VeH3H7IbaeueyTT10A+o=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 58, DateTimeKind.Local).AddTicks(9323),
                            UserName = "Darby4"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 75, DateTimeKind.Local).AddTicks(133),
                            Email = "Dixie70@yahoo.com",
                            Password = "tJB4kmnbacbYhkf8n3AW3ERMlmaOjEEG/hXI5EUKYJk=",
                            Salt = "3aZYC2LMxoy7Oaktun4OLaxZn1CI/wzPuFtvfQX3VEg=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 75, DateTimeKind.Local).AddTicks(218),
                            UserName = "Lavada_Daniel88"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 86, DateTimeKind.Local).AddTicks(8284),
                            Email = "Otha.Beer@yahoo.com",
                            Password = "syqopeBbaFyfd/UQ7xfAbl1BoZgFdI8wvQ6V2KpMw/4=",
                            Salt = "5JKzhhzAdFuPFLbq9FtRlKDhiX4rkU3nrkk1NacFt1Q=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 86, DateTimeKind.Local).AddTicks(8332),
                            UserName = "Tavares.Hartmann"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 98, DateTimeKind.Local).AddTicks(8034),
                            Email = "Bernadette89@yahoo.com",
                            Password = "Co+2Y+8Oc0a39OoWiCfkXvS/BxgD9euszL2tMj1rjso=",
                            Salt = "NYNNBQIkVZfpGdELEMGIwpuJ+JIfLDGOIXcSGSIRGRg=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 98, DateTimeKind.Local).AddTicks(8109),
                            UserName = "Angelica_Reichel15"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 110, DateTimeKind.Local).AddTicks(6029),
                            Email = "Jace.Legros42@gmail.com",
                            Password = "paMmKdU4w0M62wf4hXmaWlzfIhKM2kzxExAqh8B8bNw=",
                            Salt = "METagVut4xsd/W++OtFeZIl8/hLFBho/CAusq775GkU=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 110, DateTimeKind.Local).AddTicks(6068),
                            UserName = "Ernest_Wisozk"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 122, DateTimeKind.Local).AddTicks(4576),
                            Email = "Darryl_Greenholt@hotmail.com",
                            Password = "n5f4mpMvGP6IQSWmrG5slctR4yY/EmIqx9uqNDk11Fk=",
                            Salt = "26ZHN5prBoTvqNwGOtoRUTe61i4t732vEOi5OpBDM2M=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 122, DateTimeKind.Local).AddTicks(4648),
                            UserName = "Isai0"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 134, DateTimeKind.Local).AddTicks(1376),
                            Email = "Gregg_Abshire7@hotmail.com",
                            Password = "+3cmweKK/LyO8cDD8R/SLZG/AKkU6c4q6xIdr+K6qAE=",
                            Salt = "eF4d8D6kqphQ0sUoxR5x9T72aZK8Hh+YA3kr0gl4kPg=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 134, DateTimeKind.Local).AddTicks(1397),
                            UserName = "Marlee_Emard"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 145, DateTimeKind.Local).AddTicks(8193),
                            Email = "William_Mann39@yahoo.com",
                            Password = "tC9lkkYv5/bUA65vMjtLX/k0FlyyIwpwD19SYtPXrxg=",
                            Salt = "08TdyhDr1BWJkRqlt0lIeddxdGcNxrfkshBDbYfluXU=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 145, DateTimeKind.Local).AddTicks(8226),
                            UserName = "Robb_Fadel"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 157, DateTimeKind.Local).AddTicks(4740),
                            Email = "Stephanie81@hotmail.com",
                            Password = "T8/33WtA6ehtVYTVKARWCHcWhxDUcFXTSZPAGB8HUlM=",
                            Salt = "6ZogFTciORvkuAc9Qtzf/idGQ1H1X6POiinRcP9vZNE=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 157, DateTimeKind.Local).AddTicks(4758),
                            UserName = "Adriel_Pfeffer63"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 169, DateTimeKind.Local).AddTicks(2788),
                            Email = "Daniella_Metz@yahoo.com",
                            Password = "ajLM13w1mh8u9BtF1roJ3V1NVEdHM8leY64426nx30s=",
                            Salt = "19YzYVqnw2f1ePMp/wppEnGB1DGN/sNTTGea2WU46Ek=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 169, DateTimeKind.Local).AddTicks(3309),
                            UserName = "Stevie83"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 182, DateTimeKind.Local).AddTicks(4236),
                            Email = "Nadia_Yundt@yahoo.com",
                            Password = "dBYjlgVNIJGEVXDm2YR5LnJzIeM7Y5PEkAS5XR9jk9w=",
                            Salt = "ATtt2qjGMZDbwIS0ny2PC1ITEEOAavctGYK3pSNw3Fc=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 182, DateTimeKind.Local).AddTicks(4795),
                            UserName = "Felton0"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 195, DateTimeKind.Local).AddTicks(2050),
                            Email = "Adrien90@yahoo.com",
                            Password = "VJzV4MfCFDT9qD7UgyuKFW+Rw3YK4jjCJ4ZXnUB7ZDo=",
                            Salt = "H7vP32nbLfM6vn6zbellpu0CYlm4wwWUu4PJ2fo78no=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 195, DateTimeKind.Local).AddTicks(2493),
                            UserName = "George14"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 206, DateTimeKind.Local).AddTicks(9795),
                            Email = "Emerald.Sawayn@hotmail.com",
                            Password = "hDYYEgEpkKUEzPq3NvGfJzSSFmK7ibjsOI065Um515s=",
                            Salt = "kaqKj4eeBvndMQ0g3lZB0JrsKkF1WzKjJMubcMvOrl4=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 206, DateTimeKind.Local).AddTicks(9839),
                            UserName = "Beau72"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 218, DateTimeKind.Local).AddTicks(7699),
                            Email = "Rosalind_Smitham@yahoo.com",
                            Password = "8yTzq8qZA1c7xKbhPF4AY4wt5GnlOCFgK33HePsGBOg=",
                            Salt = "rstTFPPYt+YMNX1HkT94aLeG6nVBv4rv80ldVD/jHes=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 218, DateTimeKind.Local).AddTicks(7733),
                            UserName = "Francesca_McClure4"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 230, DateTimeKind.Local).AddTicks(4148),
                            Email = "test@gmail.com",
                            Password = "DjKf3CL4sGtoLKE9SXz+9O4DMymjnW0MlGkdWm2jSvE=",
                            Salt = "pAHAF9LIFGTzBKRc83OaOQ9RyW61fSsbY0GzAKXt1y4=",
                            UpdatedAt = new DateTime(2020, 6, 14, 19, 43, 45, 230, DateTimeKind.Local).AddTicks(4148),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
